server:
    port: 8080
spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    sql:
        init:
            encoding: UTF-8
            schema-locations:
                - classpath:schema.sql
                # - classpath:org/springframework/security/core/userdetails/jdbc/users.ddl